### ISSUE TITLE
Simulate.jl doesn´t use t or Fs or Ts

### ISSUE THREAD

**Issue by DarioSlaifsteinSk** [BradyPlanden/LiiBRA.jl#37]
Hi!,
I´m using `LiiBRA` to simulate PBROMs in the context of residential energy management systems.
Unfortunately when running some simulations I found some limitations, which I'm not sure are on my side or on the package.
First, when running `Simulate()` with a default model ($Fs=1Hz$ and $Ts=1s$) and a time array of `t=0:900:2*3600` in secs. The results, of course, are incorrect because  `Cell.RA.SamplingT=1`s when it should be 900s. Okay, perfect.
Btw, in `Simulate(....,)`, `t` is not used for any calculation, but just appended to the `Results` Tuple. Somehow assuming that $\Delta t=1s$.
Anyway I go on and do:
```julia
Cell = Construct("LG M50")
Cell.RA.Fs = 1/900 # Modify transfer function sampling frequency
Cell.RA.SamplingT = 900 # Modify final system sampling period
Cell.Const.T = 298.15 # Modify cell temperature
Cell.Const.Debug = true # Modify cell temperature
```
But in `Realise()` I get the following error:
```julia
BoundsError: attempt to access 21×17 Matrix{Float64} at index [1:21, 18]
```
in the line
```julia
    U,S,V = fh!(𝐇,Cell.RA.H1,Cell.RA.H2,puls,Cell.RA.M,Puls_L)
```
so, why? Is $Fs$ to olow? Shouldn't there be a safe somewhere? Moreover, where is `Cell.RA.Tlen` even in the picture here?

**Comment by BradyPlanden** [comment]
Hi @DarioSlaifsteinSk,

Glad to see you are using LiiBRA, although with challenges that come from a lack of documentation on my side. Taking a look at your issue above, I am having difficulties reproducing on `main`. If you can you clone the repo and activate the package locally to confirm the issue is persistent, that would be appreciated. I don't recommend using a realisation frequency of 900 hz, the computational time will be quite high and the cell dynamics shouldn't be varying this quickly.

In terms of `simulate()`, the arguement `t` is constructed in the higher-level functions such as `HPPC()` and is viewable [here](https://github.com/BradyPlanden/LiiBRA.jl/blob/a1ae688afb54d713ec5f398843a4619392413408/src/LiiBRA.jl#L86C35-L86C35). Passing it to `simulate` is no longer required, but is a legacy implementation - it is required in the `Results` dict but this could be integrated at a higher-level. 

As you can see in the `HPPC` function above, `Ts` is captured within the construction of the `t` variable.
